name: Daily Commit

on:
  schedule:
    - cron: '0 9 * * *' # Executar todos os dias às 9h UTC (ajuste conforme necessário)

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Substitua 'x' pela versão do Python que você está usando

      - name: Run script
        run: python /path/to/your/script.py
