name: Daily Commit

on:
  schedule:
  - cron: '38 18 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git
      run: |
        git config --global user.email "jv0488598@gmail.com"
        git config --global user.name "João Vitor"

    - name: Push changes
      run: |
        git commit --allow-empty -m "Commit diário automático"
        git push https://${{ secrets.PAT }}@github.com/joaovitorkc/cac-wiki2.0 HEAD:main
